# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Socket.IO-Client-Swift', '~> 15.1.0'
 pod 'TTDFKit' , :path => "../TTDFKit.podspec"
#   pod 'TTDFKit' , '~> 2.0.3'
  
end
