# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TTDFKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'TTDFKit' , :path => "../TTDFKit.podspec"
#  pod 'TTDFKit' , :path => "../../TTDFKit/TTDFKit.podspec"
end
